
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const FETCH_GENRES_START = 'FETCH_GENRES_START'
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS'
export const FETCH_GENRES_ERROR = 'FETCH_GENRES_ERROR'

export const FETCH_FILMS_START = 'FETCH_FILMS_START'
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS'
export const FETCH_FILMS_ERROR = 'FETCH_FILMS_ERROR'

export const FETCH_FILM_SUCCESS = 'FETCH_FILM_SUCCESS'
export const FETCH_FILM_ERROR = 'FETCH_FILM_ERROR'


export const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS'
export const DELETE_FILM_ERROR = 'DELETE_FILM_ERROR'

export const GENRE_SUCCESS = 'GENRE_SUCCESS'
export const GENRE_ERROR = 'GENRE_ERROR'

export const ADD_NEWGENRE = 'ADD_NEWGENRE'
export const CHANGE_GENRE = 'CHANGE_GENRE'

export const DELETE_GENRE_SUCCESS = 'DELETE_GENRE_SUCCESS'
export const DELETE_GENRE_ERROR = 'DELETE_GENRE_ERROR'


export const OPEN_MODAL_FILM = 'OPEN_MODAL_FILM'
export const CLOSE_MODAL_FILM = 'CLOSE_MODAL_FILM'

export const OPEN_MESSAGE = 'OPEN_MESSAGE'
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE'

export const ADD_FILM = 'ADD_FILM'
export const CHANGE_FILM = 'CHANGE_FILM'



